export const getQuestions = (lang: 'cs' | 'en'): string[] => {
    const cs = [
        "Radši byste bydleli ve městě, než-li na vesnici.",
        "Je pro vás absolutní prioritou bydlet mimo oblasti ohrožené povodněmi (mimo záplavová území)?",
        "Potřebujete mít v krátké docházkové vzdálenosti zastávku hromadné dopravy (MHD, autobus nebo vlak)?",
        "Je pro vás důležité mít v blízkosti bydliště (do 10 km) nemocnici nebo lékařskou pohotovost?",
        "Máte děti (nebo je plánujete) a potřebujete mít blízko mateřskou či základní školu?",
        "Zajímá vás agroturistika (farmy, statky, jízda na koni) a chcete ji mít v okolí?",
        "Je pro vás klíčové, aby se ve vašem okolí nenacházely velké průmyslové zóny nebo továrny?",
        "Je pro vás důležité mít v blízkosti kina nebo kinosály?",
        "Chcete bydlet v místě s dobrou dopravní dostupností do nejbližšího krajského města (např. do 30 minut)?",
        "Je pro vás důležité žít v oblasti s čistým ovzduším (mimo zóny s vysokou koncentrací znečišťujících látek)?",
        "Rádi navštěvujete ZOO nebo zooparky a chcete je mít v rozumné dojezdové vzdálenosti?",
        "Potřebujete mít v okolí snadno dostupnou lékárnu?",
        "Chcete mít v pěším dosahu veřejnou knihovnu?",
        "Uvítali byste mít v dojezdové vzdálenosti letiště?",
        "Láká vás život v těsné blízkosti historického centra nebo městské památkové zóny?",
        "Preferujete oblasti, kde je nízká nezaměstnanost a dobrá nabídka pracovních míst?",
        "Jste častými návštěvníky muzeí a galerií?",
        "Chtěli byste mít poblíž pedagogicko-psychologickou poradnu nebo školské poradenské zařízení?",
        "Je pro vás důležité vyhnout se oblastem, které jsou v létě extrémně ohrožené vlnami veder (nedostatek zeleně a vody)?",
        "Je pro vás důležité mít poblíž ordinaci zubního lékaře?",
        "Chcete bydlet v blízkosti hradů, zámků nebo archeologických památek?",
        "Chcete mít blízko bydliště přírodní park, rezervaci nebo chráněné území?",
        "Rádi nakupujete ve velkých supermarketech a plnosortimentních prodejnách, které chcete mít co nejblíže?",
        "Navštěvujete rádi divadla či filharmonie a chcete je mít blízko?",
        "Zajímají vás dostupnost domovů pro seniory nebo pečovatelských služeb ve vašem okolí?",
        "Chcete mít v docházkové vzdálenosti ordinaci praktického lékaře nebo pediatra?",
        "Jsou pro vás důležité domovy dětí a mládeže nebo střediska volného času pro kroužky?",
        "Chtěli byste bydlet blízko lázeňského města nebo lázní?",
        "Vadí vám vysoká hluková zátěž (např. bydlení blízko hlavních silnic, železnic či letiště)?",
        "Je pro vás důležité mít poblíž lanové nebo zábavní centrum pro rodinné výlety?",
        "Potřebujete mít v dojezdové vzdálenosti střední nebo vysokou školu?",
        "Preferujete bydlení mimo oblasti s vysokým rizikem větrné eroze (např. velké otevřené lány)?",
        "Zajímají vás hornické či technické památky ve vašem regionu?",
        "Vyhýbáte se rádi bydlení v blízkosti věznice?",
        "Požadujete lokalitu s dostupností spolehlivého a vysokorychlostního internetu?",
        "Oceníte blízkost velkých sportovišť (např. zimní stadiony, sportovní haly)?",
        "Je pro vás atraktivní mít blízko památky zapsané na seznamu UNESCO?",
        "Láká vás blízkost hudebních klubů nebo areálů pro festivaly?",
        "Oceníte v okolí hustou síť naučných stezek pro procházky?",
        "Hrajete golf a oceníte blízkost golfového hřiště?",
        "Jste milovníci piva a uvítali byste v blízkosti lokální pivovary?",
        "Oceníte v blízkosti dětské dopravní hřiště pro výuku dětí?",
        "Přáli byste si bydlet poblíž botanické zahrady nebo arboreta?",
        "Chcete mít v okolí aquapark, koupaliště nebo plavecký bazén?",
        "Je pro vás výhodné mít nedaleko sběrný dvůr nebo velkoobjemové kontejnery na odpad?",
        "Zajímají vás lokální trhy a dostupnost certifikovaných regionálních produktů?",
        "Oceníte, pokud je v obci dostupná pošta?",
        "Vyhledáváte blízkost lyžařských areálů, vleků nebo běžkařských tras?",
        "Preferujete bydlení v místě, kde není zaveden systém placených parkovacích zón?",
        "Jezdíte na kole a požadujete v okolí hustou síť cyklostezek a cyklotras?"
    ];

    const en = [
        "Do you prefer living in a city rather than a village?",
        "Is it an absolute priority for you to live outside flood-prone areas (outside floodplains)?",
        "Do you need public transport stops (public transit, bus, or train) within a short walking distance?",
        "Is it important for you to have a hospital or medical emergency within 10 km of your residence?",
        "Do you have children (or plan to) and need a kindergarten or elementary school nearby?",
        "Are you bothered by high noise pollution (e.g., living near main roads, railways, or airports)?",
        "Is it crucial for you not to have large industrial zones or factories in your vicinity?",
        "Is it important for you to have a cinema or movie theaters nearby?",
        "Do you want to live somewhere with good transport access to the nearest regional capital (e.g., within 30 minutes)?",
        "Is it important for you to live in an area with clean air (outside zones with a high concentration of pollutants)?",
        "Do you enjoy visiting zoos or zooparks and want them within reasonable driving distance?",
        "Do you need an easily accessible pharmacy nearby?",
        "Do you want a public library within walking distance?",
        "Would you appreciate having an airport within driving distance?",
        "Are you attracted to living very close to a historical center or a municipal conservation area?",
        "Do you prefer areas with low unemployment and a good supply of jobs?",
        "Are you a frequent visitor to museums and galleries?",
        "Would you like an educational-psychological counseling center nearby?",
        "Is it important to avoid areas globally exposed to heatwaves in summer (lack of greenery and water)?",
        "Is it important for you to have a dentist's office nearby?",
        "Do you want to live near castles, chateaus, or archaeological monuments?",
        "Do you want to live near a nature park, reserve, or protected area?",
        "Do you like shopping in large supermarkets and want them as close as possible?",
        "Do you enjoy theaters or philharmonic halls and want them near?",
        "Are you interested in the availability of retirement homes or care services in your area?",
        "Do you want a general practitioner's or pediatrician's office within walking distance?",
        "Are children's and youth centers or leisure facilities important to you?",
        "Would you like to live near a spa town or spa center?",
        "Are you interested in agrotourism (farms, horseback riding) and want it nearby?",
        "Is it important to have a rope park or amusement center for family trips nearby?",
        "Do you need a high school or university within driving distance?",
        "Do you prefer living outside areas with a high risk of wind erosion (e.g., large open fields)?",
        "Are you interested in mining or industrial monuments in your region?",
        "Do you prefer avoiding living near a prison?",
        "Do you require a location with reliable, high-speed internet access?",
        "Do you appreciate the proximity of large sports facilities (e.g., winter stadiums, sports halls)?",
        "Is it attractive to have UNESCO world heritage sites nearby?",
        "Are you attracted to the proximity of music clubs or festival grounds?",
        "Do you appreciate a dense network of educational trails for walking in the area?",
        "Do you play golf and appreciate the proximity of a golf course?",
        "Are you a beer lover and would appreciate local breweries nearby?",
        "Would you appreciate a children's traffic park nearby for teaching children?",
        "Would you like to live near a botanical garden or arboretum?",
        "Do you want an aquapark, public swimming pool, or swimming pool in the area?",
        "Is it convenient for you to have a recycling center or large-capacity waste containers nearby?",
        "Are you interested in local markets and the availability of certified regional products?",
        "Do you appreciate it if a post office is accessible in the municipality?",
        "Are you looking for the proximity of ski resorts, lifts, or cross-country trails?",
        "Do you prefer living where there is no paid parking zone system?",
        "Do you cycle and require a dense network of cycle paths and cycle routes nearby?"
    ];

    return Array.from({ length: 50 }, (_, i) => {
        if (lang === 'cs') {
            return cs[i] || `Doplňující otázka k vašim preferencím č. ${(i + 1)}`;
        } else {
            return en[i] || `Additional preference question number ${(i + 1)}`;
        }
    });
};